Replaced give admin button with permissions widget
multitheftauto/mtasa-resources pull request #208
Opened 2020-05-27 20:26 UTC by iiN3xT

As requested in #107

![perms](https://user-images.githubusercontent.com/39503700/83068722-6d140a80-a071-11ea-8cd2-d97b91ed6744.png)

2020-11-11 08:32 UTC, jlillis requested changes
This PR currently contains merge conflicts. If you can resolve them and address the grammar of some of the messages then I think this is ready to merge.

2020-11-11 08:32 UTC, jlillis commented on [admin]/admin2/client/widgets/admin_permissions.lua
> +                if (messageBox('Are you sure to give "' .. group .. '"?', MB_QUESTION, MB_YESNO)) then
I think a better message would be "Are you sure you want to add [player] to the '[group name]' group?"

2020-11-11 08:32 UTC, jlillis commented on [admin]/admin2/client/widgets/admin_permissions.lua
> +                if (messageBox('Are you sure to revoke "' .. group .. '"?', MB_QUESTION, MB_YESNO)) then
I think a better message would be "Are you sure you want to remove [player] from the '[group name]' group?"

2020-11-11 08:32 UTC, jlillis commented on [admin]/admin2/conf/messages.xml
> +      <log>ADMIN: $admin has revoked $data group from $player</log>
Again, I think it would be better to say "[player] has been removed from the [group] group."

2021-05-14 18:51 UTC, iDannz-Breno commented
if someone is going to finish this, it may be worth adding the changes added in #324

2021-06-07 21:07 UTC, jlillis commented
Going to close this PR as it has become stale. Feel free to reopen it in the future if you find time to address the above comments.

2021-06-07 21:07 UTC, closed without merging