editor: #244 organizational output setting
multitheftauto/mtasa-resources pull request #245
Opened 2020-11-08 19:03 UTC by umithyo

2020-11-08 20:18 UTC, xLive commented on [editor]/editor_main/meta.xml
> +        <setting name="#mapResourceOrganizationalDirectory"
How to change this setting?
because it can't be changed by the admin panel
read about access modifiers:
https://wiki.multitheftauto.com/wiki/Settings_system

Also without a default `value` the setting won't show in the admin panel
https://github.com/multitheftauto/mtasa-resources/blob/c4e453e770067dfa8761e04aba3cf579b37bcd23/%5Badmin%5D/admin/server/admin_settings.lua#L32
so I suggest a value like none or false
```suggestion
        <setting name="*mapResourceOrganizationalDirectory" value="none"
```

2020-11-09 10:48 UTC, umithyo commented on [editor]/editor_main/server/saveloadtest_server.lua
> +local mapResourceOrganizationalDirectory = get("mapResourceOrganizationalDirectory");
Sorry the old habits :)

2020-11-09 10:49 UTC, umithyo commented on [editor]/editor_main/meta.xml
> +        <setting name="#mapResourceOrganizationalDirectory"
Does "none" equal to "nil" in lua?

2020-11-09 11:04 UTC, xLive commented on [editor]/editor_main/meta.xml
> +        <setting name="#mapResourceOrganizationalDirectory"
> Does "none" equal to "nil" in lua?

Nope, it's just a string, you need to add that in your code
like other resources like `race` for example
 https://github.com/multitheftauto/mtasa-resources/blob/c4e453e770067dfa8761e04aba3cf579b37bcd23/%5Bgamemodes%5D/%5Brace%5D/race/meta.xml#L113

> you can change the setting in meta.xml. I thought that would be more convenient.

I think it's easier for mappers to be in the admin panel
Thoughts?

2020-11-10 01:39 UTC, jlillis commented on [editor]/editor_main/meta.xml
> +        <setting name="#mapResourceOrganizationalDirectory"
It should be standard practice to make all settings available in the admin panel with proper titles, descriptions, and default values. This is how the settings system is intended to be used.

2020-11-10 15:08 UTC, umithyo commented on [editor]/editor_main/meta.xml
> +        <setting name="#mapResourceOrganizationalDirectory"
Alright, done

2020-11-10 20:21 UTC, jlillis requested changes
Looking good so far, just need to make a few tweaks and this is ready to merge.

2020-11-10 20:21 UTC, jlillis commented on [editor]/editor_main/meta.xml
> +            accept = "*"
Fix indentation

2020-11-10 20:21 UTC, jlillis commented on [editor]/editor_main/meta.xml
> +			desc="Organizational directory for newly added map resources."
You should add a note here that the directory name must be in [brackets].

2020-11-10 20:21 UTC, jlillis commented on [editor]/editor_main/server/saveloadtest_server.lua
> +local mapResourceOrganizationalDirectory = get("mapResourceOrganizationalDirectory") ~= "none" and get("mapResourceOrganizationalDirectory") or nil
You should consider moving this down to line 360 (just above the call to `createResource`), that way the player can change the organizational directory while the editor is running. Also, you should add some code to validate the organizational directory which needs to be in [brackets]. I don't recall if createResource will add brackets to the directory name or not.

2020-11-10 21:03 UTC, umithyo commented on [editor]/editor_main/meta.xml
> +            accept = "*"
Indentation looks fine on my editor. How can I fix this?
![image](https://user-images.githubusercontent.com/12802646/98733225-417fa500-23b1-11eb-949d-d88aff1cee78.png)

2020-11-10 21:05 UTC, Woovie commented on [editor]/editor_main/meta.xml
> +            accept = "*"
I see a mix of spaces and tabs. Probably part of the issue.

2020-11-10 21:05 UTC, umithyo commented on [editor]/editor_main/server/saveloadtest_server.lua
> +local mapResourceOrganizationalDirectory = get("mapResourceOrganizationalDirectory") ~= "none" and get("mapResourceOrganizationalDirectory") or nil
I tested it, it will not add brackets.
Should I use regex for checking the brackets?

2020-11-10 21:17 UTC, jlillis commented on [editor]/editor_main/meta.xml
> +            accept = "*"
Same here, and in the diff viewer on GitHub. We generally use 4 spaces instead of tabs.

2020-11-10 21:17 UTC, jlillis commented on [editor]/editor_main/server/saveloadtest_server.lua
> +local mapResourceOrganizationalDirectory = get("mapResourceOrganizationalDirectory") ~= "none" and get("mapResourceOrganizationalDirectory") or nil
Yes, that's what I would do.

2020-11-11 06:27 UTC, xLive commented on [editor]/editor_main/meta.xml
> +			friendlyname="Map resource organizational directory"
I think we need a shorter name?
![image](https://user-images.githubusercontent.com/30420446/98776501-196b6280-2400-11eb-9619-7ead322fa0ab.png)

2020-11-11 10:12 UTC, qaisjp commented on [editor]/editor_main/meta.xml
> +			friendlyname="Map resource organizational directory"
"Map base directory"

2020-11-13 21:36 UTC, umithyo commented on [editor]/editor_main/meta.xml
> +            accept = "*"
So, is there anything I can do about this? Put 4 spaces instead of a tab?

2020-11-13 21:37 UTC, umithyo commented on [editor]/editor_main/server/saveloadtest_server.lua
> +local mapResourceOrganizationalDirectory = get("mapResourceOrganizationalDirectory") ~= "none" and get("mapResourceOrganizationalDirectory") or nil
What should the user get if they didn't follow the right format? An error message or should I just continue as if the option has never been passed? i.e `createResource(resourceName)`

2020-11-13 22:24 UTC, qaisjp commented on [editor]/editor_main/meta.xml
> +            accept = "*"
1. Click "Spaces: 4" or "Tabs: 4" in the bottom of vscode ![image](https://user-images.githubusercontent.com/923242/99126842-dc20f380-25fe-11eb-8b10-68e3531866a2.png)
2.  then click "Convert indentation to spaces" ![image](https://user-images.githubusercontent.com/923242/99126885-ee9b2d00-25fe-11eb-9b75-b2b6a889c992.png)

2020-11-13 22:25 UTC, qaisjp commented on [editor]/editor_main/meta.xml
> +            accept = "*"
Also, you can view whitespace in the editor by changing this setting to something else ![image](https://user-images.githubusercontent.com/923242/99126981-22765280-25ff-11eb-802d-09475335cc85.png)

2020-11-14 01:31 UTC, jlillis commented on [editor]/editor_main/server/saveloadtest_server.lua
> +local mapResourceOrganizationalDirectory = get("mapResourceOrganizationalDirectory") ~= "none" and get("mapResourceOrganizationalDirectory") or nil
A debugscript error would be fine.

2020-11-14 13:12 UTC, qaisjp commented on [editor]/editor_main/meta.xml
> +            accept = "*"
Oh, it looks like it previously used tabs instead of spaces. Please could you click "Convert indentation to tabs" instead?

2020-11-14 13:16 UTC, umithyo commented on [editor]/editor_main/meta.xml
> +            accept = "*"
Okay, done

2020-11-14 13:17 UTC, umithyo commented on [editor]/editor_main/server/saveloadtest_server.lua
> +local mapResourceOrganizationalDirectory = get("mapResourceOrganizationalDirectory") ~= "none" and get("mapResourceOrganizationalDirectory") or nil
Added the check and error

2020-11-14 13:21 UTC, qaisjp commented on [editor]/editor_main/meta.xml
> +            accept = "*"
you need to do it for [editor]/editor_main/server/saveloadtest_server.lua please

2020-11-14 13:22 UTC, umithyo commented on [editor]/editor_main/meta.xml
> +            accept = "*"
Sorry, done

2020-11-14 23:18 UTC, jlillis approved these changes

2020-11-22 22:55 UTC, jlillis commented
This all seems to work well, but I was wondering if you'd be interested in also modifying the editor save/load GUI to show the organizational directory and maybe allow it to be changed from there. It would be a bit better from a usability standpoint. If you'd rather call this finished I'm also happy to just merge it.

2020-11-23 10:35 UTC, umithyo commented
> This all seems to work well, but I was wondering if you'd be interested in also modifying the editor save/load GUI to show the organizational directory and maybe allow it to be changed from there. It would be a bit better from a usability standpoint. If you'd rather call this finished I'm also happy to just merge it.

I think that makes sense to show it in the save/load GUI as well, thanks for the suggestion. I will work on it as soon as I'm available.

2020-11-23 13:56 UTC, xLuxy commented
What about backups?
https://github.com/multitheftauto/mtasa-resources/blob/e51ed2fb1736c547ca0c7984d43a161d2c6872ac/%5Beditor%5D/editor_main/server/save_backup.lua#L18

2020-11-23 15:11 UTC, jlillis commented
> 
> What about backups?

What about them?

2021-01-27 11:47 UTC, umithyo commented
I don't think I will be able to do add these settings into save/load GUI for a while. Sorry for the long wait. Can we merge this and look into it later?

2021-01-28 23:23 UTC, jlillis commented
Sure, I'll merge this for now and open a feature request for that separately.

2021-01-28 23:23 UTC, merged