race: end the map when only spectators are left
multitheftauto/mtasa-resources pull request #254
Opened 2020-11-23 10:02 UTC by xLive

Fixes #191

2020-11-23 12:38 UTC, jlillis reviewed
This code looks fine. I don't have a server with more than one player (myself) to test it on - could another reviewer try this out?

2020-12-05 23:59 UTC, jlillis requested changes
This PR looks good but currently contains merge conflicts. Once you resolve this, I'd be happy to merge.

2020-12-06 06:58 UTC, xLive commented
done

2020-12-13 04:50 UTC, jlillis approved these changes

2020-12-13 04:50 UTC, merged