editor: replaced WARNING with INFO
multitheftauto/mtasa-resources pull request #258
Opened 2020-12-03 13:27 UTC by turret001

hi, I always thought WARNING was a bit of an error message with red text and all so I replaced WARNING: string with INFO: and changed the text to appear as yellow instead of red.

this message appears when you start Editor resource while freeroam is running.

2020-12-03 13:56 UTC, Dezash commented on [editor]/editor_main/server/freeroam.lua
> +			outputDebugString (  "INFO: 'FREEROAM' resource is currently running.  The resource has been shut off as a precaution!" )
```suggestion
			outputDebugString (  "'FREEROAM' resource is currently running.  The resource has been shut off as a precaution!" )

```
No need for 'info' here because it's prefixed automatically by outputDebugString

2020-12-05 23:25 UTC, jlillis requested changes

2020-12-05 23:25 UTC, jlillis commented on [editor]/editor_main/server/freeroam.lua
> +			outputDebugString (  "'FREEROAM' resource is currently running.  The resource has been shut off as a precaution!" )
Maybe make this a [custom message (type=4)](https://wiki.multitheftauto.com/wiki/OutputDebugString) and color it orange?

2020-12-05 23:25 UTC, jlillis commented on [editor]/editor_main/server/freeroam.lua
> +
Extra newline

2020-12-12 13:08 UTC, turret001 commented on [editor]/editor_main/server/freeroam.lua
> +			outputDebugString (  "'FREEROAM' resource is currently running.  The resource has been shut off as a precaution!" )
I'd like to keep it as-is for now. Orange is close to red so it might feel like an error as well

2020-12-12 13:12 UTC, turret001 commented on [editor]/editor_main/server/freeroam.lua
> +
I'm sorry I'm a total noob when it comes to Lua & Github. I'm ok with adding an empty line but I don't know how to approve your change

2020-12-12 13:43 UTC, xLive commented on [editor]/editor_main/server/freeroam.lua
> +
> 
> 
> I'm sorry I'm a total noob when it comes to Lua & Github. I'm ok with adding an empty line but I don't know how to approve your change

since it's one line you can remove it from github itself **in your fork**
![image](https://user-images.githubusercontent.com/30420446/101985079-b38c2800-3c96-11eb-8b8b-ebab14dbd7b3.png)

and choose to commit directly

or I remember you using github desktop right? do your changes there and commit & push 
and the changes will come here directly

2020-12-12 13:49 UTC, turret001 commented on [editor]/editor_main/server/freeroam.lua
> +			outputDebugString (  "'FREEROAM' resource is currently running.  The resource has been shut off as a precaution!" )
on a second thought, setting it a custom message might make the script non backwards compatible, so I'll hold off with the type 4 change

2020-12-13 04:48 UTC, jlillis approved these changes
lgtm

2020-12-13 04:49 UTC, merged