admin: fix output message on actions
multitheftauto/mtasa-resources pull request #285
Opened 2021-01-26 19:32 UTC by andr0xy

![admin](https://user-images.githubusercontent.com/73851736/105894858-84860780-5ff3-11eb-87fe-d2918ab01290.png)

It happens when a player has % after his nickname, the output message isn't complete.
That PR fixes it.

2021-01-26 22:59 UTC, xLuxy requested changes

2021-01-26 22:59 UTC, xLuxy commented on [admin]/admin/server/admin_server.lua
> +		function aEscapeNickname( name )
Make this a local function (otherwise you're defining it on the global scope in which case you can put that function somewhere else - which is unnecessary in our case)

2021-01-26 22:59 UTC, xLuxy commented on [admin]/admin/server/admin_server.lua
> +			if string.find( name, "%%" ) then
There's no need for this if statement to be here

2021-03-02 04:19 UTC, Dutchman101 approved these changes

2021-03-02 04:20 UTC, merged