headshot: minor improvements
multitheftauto/mtasa-resources pull request #290
Opened 2021-02-13 08:16 UTC by majqqq

👋🏻
- Removed triggerEvent, in fact there's no need for it, since no other resource use it.
- Replaced getRootElement() with root predefined variable.
- Switched to non-anonymous functions.

2021-02-13 08:22 UTC, jlillis requested changes
Removing the onPlayerHeadshot API event will break other resources that depend upon it. If you reverse that change, we can then approve the rest of this PR.

2021-02-13 08:30 UTC, majqqq commented
My bad, fixed :)

2021-02-13 09:14 UTC, jlillis approved these changes

2021-02-13 09:28 UTC, Dezash commented on [gameplay]/headshot/headshot.lua
> +function onPlayerSpawn()
Function name could be more clear, how about **restoreHead**?

2021-02-13 09:28 UTC, Dezash commented on [gameplay]/headshot/headshot.lua
> +function onPlayerDamage(attacker, weapon, bodypart, loss)
How about renaming this function to **headshotCheck**?

2021-02-13 09:48 UTC, majqqq commented on [gameplay]/headshot/headshot.lua
> +function onPlayerSpawn()
Since it is a binded to event, i suggest: **onPlayerSpawnRestoreHead**

2021-02-13 09:49 UTC, majqqq commented on [gameplay]/headshot/headshot.lua
> +function onPlayerDamage(attacker, weapon, bodypart, loss)
According to what i've wrote above, maybe: **onPlayerDamageHeadshot**

2021-02-13 10:10 UTC, Dezash commented on [gameplay]/headshot/headshot.lua
> +function onPlayerDamage(attacker, weapon, bodypart, loss)
**handleDamage**?

2021-02-13 10:11 UTC, Dezash commented on [gameplay]/headshot/headshot.lua
> +function onPlayerSpawn()
In that case, I would go with **handleSpawn**

2021-02-13 10:15 UTC, jlillis commented on [gameplay]/headshot/headshot.lua
> +function onPlayerSpawn()
I think your original function name was acceptable, but if you want something more "ideal" I recommend a name that simply indicates what the function does: `restorePlayerHead` would be my first choice.

Also, you could make this function local.

2021-02-13 10:16 UTC, jlillis commented on [gameplay]/headshot/headshot.lua
> +function onPlayerDamage(attacker, weapon, bodypart, loss)
As mentioned above the "ideal" name might be "checkForHeadshot" - but your original name is acceptable too. Again, this function could be local.

2021-02-13 10:36 UTC, majqqq commented on [gameplay]/headshot/headshot.lua
> +function onPlayerDamage(attacker, weapon, bodypart, loss)
> this function could be local.
Do you want to enforce local functions everywhere where it is possible or just for events? Would be nice to know when i'll work on other resources :)

2021-02-13 10:40 UTC, jlillis commented on [gameplay]/headshot/headshot.lua
> +function onPlayerDamage(attacker, weapon, bodypart, loss)
It's not a hard requirement, it's just considered good practice to do where possible. Local functions are slightly faster than global ones.

2021-02-13 10:41 UTC, majqqq commented on [gameplay]/headshot/headshot.lua
> +function onPlayerDamage(attacker, weapon, bodypart, loss)
Yeah i'm aware of it, thanks for answer.

2021-02-15 23:36 UTC, jlillis approved these changes

2021-02-15 23:36 UTC, merged