reload: few changes
multitheftauto/mtasa-resources pull request #292
Opened 2021-02-13 12:05 UTC by majqqq

Client:
- Replaced anonymous function with non anonymous, it's called reloadWeapon now.
- Renamed function **reloadWeapon** -> **reloadTimer** since it's called via timer.
- Due of that reloadWeapon it's now used as command handler/bind.
- triggerServerEvent uses localPlayer instead of resourceRoot.

Server:
- Localized event function.
- Added if check for client, according [to this wiki article.](https://wiki.multitheftauto.com/wiki/Script_security)
- Event's bound element changed to root, so it could also accept player as a source element.

2021-02-13 12:54 UTC, jlillis requested changes

2021-02-13 12:54 UTC, jlillis commented on [gameplay]/reload/reload.lua
> +	if client then
This check is not needed; `client` is guaranteed to be valid.

2021-02-13 12:54 UTC, jlillis commented on [gameplay]/reload/reload.lua
> +addEventHandler("relWep", root, reloadWeapon)
It would be better to leave this as `resourceRoot`, [according to the wiki](https://wiki.multitheftauto.com/wiki/TriggerServerEvent).

2021-02-13 12:54 UTC, jlillis commented on [gameplay]/reload/reload_c.lua
> +    triggerServerEvent("relWep", localPlayer)
Again, better to stick with `resourceRoot` here.

2021-02-13 13:06 UTC, majqqq commented on [gameplay]/reload/reload.lua
> +addEventHandler("relWep", root, reloadWeapon)
I disagree.
theElement (sourceElement) is a 3rd argument in triggers. Bound element in event handlers defines which elements can actually trigger an event function, so it's a completely different thing. Some more information:
![image](https://user-images.githubusercontent.com/51768772/107850700-a14c7880-6e04-11eb-8c9e-3ddc9406bc0b.png)
![image](https://user-images.githubusercontent.com/51768772/107850710-ac070d80-6e04-11eb-9be0-319e6029ceac.png)

2021-02-13 13:18 UTC, majqqq commented on [gameplay]/reload/reload.lua
> +	if client then
If it's guaranteed i'm wondering why it's still appearing in this article, perhaps it is outdated a bit (last edit in 2017). I will push commit after your opinion on resourceRoot.

2021-02-13 13:20 UTC, jlillis commented on [gameplay]/reload/reload.lua
> +addEventHandler("relWep", root, reloadWeapon)
Had to re-read this a few times - you're right, the disclaimer was for triggering events as root, not attaching event handlers to root.

2021-02-13 13:23 UTC, jlillis commented on [gameplay]/reload/reload.lua
> +	if client then
The advice, as I understand it, is that the variable `client` can be trusted to be the client that triggered the event. This is different from the `source` of the event - theoretically, a malicious client could trigger a server event and pass a different player as the source. For this resource the client is always going to be the source so we don't need to bother with checking anything.

2021-02-13 13:25 UTC, majqqq commented on [gameplay]/reload/reload.lua
> +	if client then
Done.

2021-02-15 23:35 UTC, jlillis approved these changes

2021-02-15 23:35 UTC, merged