play: refactor
multitheftauto/mtasa-resources pull request #363
Opened 2021-11-02 05:49 UTC by srslyyyy

Refactored play gamemode.
- Fixed memory leak (timer was never cleared from table).
- Optimised code.
- Disabled OOP (it's not worth to use it for some simple methods).
- Improved readability.
- Logic has been separated per parts, so it will be easier to maintain/work on.

Tested briefly, hope that i didn't missed anything.

2021-11-02 07:20 UTC, Disinterpreter commented
I think it's better to move datasets out, like `dataset.lua` with arrays.
Player array shouldn't be one liner.

2021-11-02 07:41 UTC, srslyyyy commented
Moved them to **play_config.lua**, and fixed one liner.

2021-11-02 07:43 UTC, Disinterpreter commented
> Do you also need for playerSkins to not be one liner?

yes

2021-11-02 11:07 UTC, srslyyyy commented
Done & waiting for further feedback.

2021-11-04 13:22 UTC, TheNormalnij commented on [gamemodes]/[play]/play/play_config.lua
> +	{557, -676.67596435547, 968.88238525391, 12.507817268372, 89.458343505859},
Why we don't use a resource file and EDF for positions? Hardcoded stuff is a bad practice in programming.

2021-11-07 14:34 UTC, TheNormalnij requested changes

2021-11-07 14:34 UTC, TheNormalnij commented on [gamemodes]/[play]/play/play.lua
> +	end
This looks better for me
```lua
	for playerID = 1, #playersTable do
		playSpawnPlayer( playersTable[playerID] )
	end
```

2021-11-07 14:34 UTC, TheNormalnij commented on [gamemodes]/[play]/play/play_players.lua
> +	if validPlayer then
Same
```lua
if isElement(playerElement) then
```

2021-11-07 14:34 UTC, TheNormalnij commented on [gamemodes]/[play]/play/play_players.lua
> +	else
I think here should be 2 different  functions

2021-11-07 14:34 UTC, TheNormalnij commented on [gamemodes]/[play]/play/play_vehicles.lua
> +		createPlayVehicle(vehicleData)
```lua
createPlayVehicle( vehicleSpawns[vehicleID] )
```

2021-11-07 14:34 UTC, TheNormalnij commented on [gamemodes]/[play]/play/play_vehicles.lua
> +	end
```lua
if isElement(vehicleElement) then
```

2021-11-07 14:34 UTC, TheNormalnij commented on [gamemodes]/[play]/play/play_vehicles.lua
> +			if validVehicle then
Same

2021-11-07 14:34 UTC, TheNormalnij commented on [gamemodes]/[play]/play/play_vehicles.lua
> +		if validTimer then
```lua
if isTimer(vehicleTimer) then
```

2021-11-07 14:34 UTC, TheNormalnij commented on [gamemodes]/[play]/play/play_vehicles.lua
> +end
```lua
if isElement(source) and getElementType(source) == "vehicle" then
    destroyVehicleTimer(source)
    vehiclesToSpawn[source] = nil
end

2021-11-08 13:03 UTC, srslyyyy commented on [gamemodes]/[play]/play/play.lua
> +	end
I'd say this is somewhat personal preference. I used to do that in past but not anymore, Also saving to variable means less indexing in later stages, when someone might add something else here.

2021-11-08 13:03 UTC, srslyyyy commented on [gamemodes]/[play]/play/play_players.lua
> +	if validPlayer then
As above.

2021-11-08 13:04 UTC, srslyyyy commented on [gamemodes]/[play]/play/play_players.lua
> +	else
Why not make use of predefined variable?

2021-11-08 13:05 UTC, srslyyyy commented on [gamemodes]/[play]/play/play_config.lua
> +	{557, -676.67596435547, 968.88238525391, 12.507817268372, 89.458343505859},
Might be good idea, but i never used EDFs, so will look into it soon. Also, this might be optional.

2021-11-08 13:16 UTC, jlillis commented on [gamemodes]/[play]/play/play_config.lua
> +	{557, -676.67596435547, 968.88238525391, 12.507817268372, 89.458343505859},
Spawns were defined in a .map file until #73 was merged. It states that this is a "more efficient" approach. I personally don't agree with that choice but that's the story.

2021-11-08 16:58 UTC, TheNormalnij commented on [gamemodes]/[play]/play/play_players.lua
> +	else
Because it's unnecessarily complex.
Be better:
```lua
function onPlayerJoin()
    playSpawnPlayer(source)
end

function onPlayerWasted()
    ...
end
```

2021-11-08 17:42 UTC, TheNormalnij commented on [gamemodes]/[play]/play/play.lua
> +	end
I think we can't using extra variables unless it makes code harder to read. I believe it's a good practice for complex conditions
 ```lua
 local playerOneValid = isElement( playerOne ) and playerOne:getHealth() > 50
 local playerTwoValid = isElement( playerTwo ) and playerTwo:getHealth() > 50
 local playerThreeValid = isElement( playerThree ) and playerThree:getData( "smt" ) < 3
 
 if ((playerOneValid or playerTwoValid) and playerThreeValid) then
     ...
 end
 ```
I haven't see any code guide that recommends using extra variables for small conditionals and something else. So i think avoiding is most common practice.

2021-11-08 19:52 UTC, Dutchman101 commented on [gamemodes]/[play]/play/play_config.lua
> +	{557, -676.67596435547, 968.88238525391, 12.507817268372, 89.458343505859},
> Hardcoded stuff is a bad practice in programming

> It states that this is a "more efficient" approach. I personally don't agree



For existing features of the play gamemode (and their reliability) it has to be done like this.. setting vehicles on spawn undamagable until used, freezing them, destroy timer, checks to respawn them so as to make sure that players won't run out of spawn vehicles. They are all desired things for this gamemode and cannot be reliably done in .map/edf

2021-11-08 21:30 UTC, TheNormalnij commented on [gamemodes]/[play]/play/play_config.lua
> +	{557, -676.67596435547, 968.88238525391, 12.507817268372, 89.458343505859},
For this PR it's ok. But It can be done via custom element of type "spawnpoint_vehicle" for vehicles spawner positions. Old system just used "vehicle" type in .map. Other gamemodes are mostly well designed for the map editor.

2021-11-16 12:43 UTC, srslyyyy commented
@TheNormalnij, @jlillis updated, re-review please.

2021-11-16 21:29 UTC, TheNormalnij commented
LGTM. We need test it before merge.

2021-11-21 14:02 UTC, ArranTuna commented on [gamemodes]/[play]/play/play.lua
> +	for playerID = 1, #playersTable do
What's wrong with "for i, player in ipairs(getElementsByType("player"))" do?

2021-11-21 15:33 UTC, srslyyyy commented on [gamemodes]/[play]/play/play.lua
> +	for playerID = 1, #playersTable do
@ArranTuna yes.

2022-04-18 16:22 UTC, patrikjuvonen requested changes

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/meta.xml
>  		<setting name="*vehicleRespawnTime" value="[60000]" friendlyname="Vehicle respawn time" group="Spawnpoint vehicles" desc="Vehicle respawn time after it is taken. Anything below 50 is auto-set to 50
Inconsistent spacing.
```suggestion
		<setting name="*playerRespawnTime" value="[4000]" friendlyname="Player respawn time" desc="Player respawn time after dying in milliseconds. Anything below 50 is auto-set to 50"/>
		<setting name="*vehicleRespawnTime" value="[60000]" friendlyname="Vehicle respawn time" group="Spawnpoint vehicles" desc="Vehicle respawn time after it is taken. Anything below 50 is auto-set to 50"/>

```

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/meta.xml
> +</meta>
Missing newline at the end of the file.
```suggestion
</meta>

```

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/play_config.lua
> +}
Missing newline at the end of the file.
```suggestion
}

```

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/play.lua
> +addEventHandler("onResourceStart", resourceRoot, onResourceStartPlay)
Missing newline at the end of the file.
```suggestion
addEventHandler("onResourceStart", resourceRoot, onResourceStartPlay)

```

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/play_players.lua
> +end
Missing newline at the end of the file.
```suggestion
end

```

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/play_vehicles.lua
> +end
Missing newline at the end of the file.
```suggestion
end

```

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/play_players.lua
> +	playerRespawnTime = playerRespawnTime > 50 and playerRespawnTime or 50
Timers support shorter durations than 50ms nowadays.
```suggestion
	playerRespawnTime = playerRespawnTime > 0 and playerRespawnTime or 0
```

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/play_vehicles.lua
> +	vehicleExpireTime = vehicleExpireTime > 50 and vehicleExpireTime or 50
Timers support shorter durations than 50ms nowadays.
```suggestion
	vehicleExpireTime = vehicleExpireTime > 0 and vehicleExpireTime or 0
```

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/play_vehicles.lua
> +	vehicleRespawnTime = vehicleRespawnTime > 50 and vehicleRespawnTime or 50
Timers support shorter durations than 50ms nowadays.
```suggestion
	vehicleRespawnTime = vehicleRespawnTime > 0 and vehicleRespawnTime or 0
```

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/meta.xml
>  		<setting name="*vehicleRespawnTime" value="[60000]" friendlyname="Vehicle respawn time" group="Spawnpoint vehicles" desc="Vehicle respawn time after it is taken. Anything below 50 is auto-set to 50
Also, if you do change the minimum timer duration, remember to update the setting descriptions accordingly.

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/play.lua
> +function onResourceStartPlay()
Would a local function work?
```suggestion
local function onResourceStartPlay()
```

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/play_players.lua
> +		local randomSpawn = math.random(1, spawnsCount)
The 1 is unnecessary.
```suggestion
		local randomSpawn = math.random(spawnsCount)
```

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/play_players.lua
> +		local randomSkin = math.random(1, skinsCount)
The 1 is unnecessary.
```suggestion
		local randomSkin = math.random(skinsCount)
```

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/play_players.lua
> +		setCameraTarget(playerElement, playerElement)
The second argument is unnecessary.
```suggestion
		setCameraTarget(playerElement)
```

2022-04-18 16:22 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/play_vehicles.lua
> +	local modelID, posX, posY, posZ, rotX = vehicleData[1], vehicleData[2], vehicleData[3], vehicleData[4], vehicleData[5]
You can use [unpack](https://www.lua.org/manual/5.1/manual.html#pdf-unpack) to easily get the table elements.
```suggestion
	local modelID, posX, posY, posZ, rotX = unpack(vehicleData)
```

2022-04-22 09:19 UTC, patrikjuvonen requested changes

2022-04-22 09:19 UTC, patrikjuvonen commented on [gamemodes]/[play]/play/play_players.lua
> +		local posX, posY, posZ, rotX = spawnData[1], spawnData[2], spawnData[3], spawnData[4]
Sorry I missed this one. Let's use [unpack](https://www.lua.org/manual/5.1/manual.html#pdf-unpack) here as well.
```suggestion
		local posX, posY, posZ, rotX = unpack(spawnData)
```

2022-04-22 10:14 UTC, patrikjuvonen approved these changes

2022-06-14 00:15 UTC, jlillis approved these changes

2022-12-29 20:00 UTC, patrikjuvonen commented
Thank you.

2022-12-29 20:00 UTC, merged