Remove legacy json lib
multitheftauto/mtasa-resources pull request #383
Opened 2022-04-07 10:32 UTC by 4O4

Last modifications made to `json.js` lib during webmap upgrade ([[web]/ajax/json.js](https://github.com/multitheftauto/mtasa-resources/commit/8e2b12b6d012c89a063a8c5e9873454f8d3ab7e3#diff-adfe7968957f2a79a6ec34240a7f5d87186a3b1a64b8c52baa91f1f78c5c7a29)) broke other resources. This lib however is no longer needed as there have been native JSON functions in Javascript for ages already.

This PR reverts a workaround previously introduced in #358, removes the old lib and replaces it with native JSON functions. 

This also involved a slight refactoring. A bit of more modern code was introduced (`class`es, `startsWith`). I'm assuming we don't care about ancient browsers anymore and ES2015 is a safe target for any new JS code.

Closes #379 #358

2022-04-18 15:45 UTC, patrikjuvonen requested changes
Requesting for clarification at least on the http exports part.

2022-04-18 15:45 UTC, patrikjuvonen commented on [web]/ajax/ajax.js
>  			var element = this.elements[i];
Prefer [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of).

```suggestion
		for (const element of this.elements) {

```

2022-04-18 15:45 UTC, patrikjuvonen commented on [web]/ajax/ajax.js
>  			var resource = this.resources[i];
Prefer [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of).
```suggestion
		for (const resource of this.resources) {
```

2022-04-18 15:45 UTC, patrikjuvonen commented on [web]/elementbrowser/script.js
> +				dataList += key + " = " + (typeof(data[key]) === "object" ? JSON.stringify(data[key]) : data[key]) + ", ";
This for loop should be refactored to use [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of).

2022-04-18 15:45 UTC, patrikjuvonen commented on [web]/resourcemanager/manager.lua
> -end
By removing these functions, are we breaking backwards compatibility for the exported http functions?
https://github.com/4O4/mtasa-resources/blob/bugfix/remove-legacy-ajax-json-lib/%5Bweb%5D/resourcemanager/meta.xml#L8-L16

2022-04-18 18:40 UTC, 4O4 commented on [web]/resourcemanager/manager.lua
> -end
Nope, nothing gets broken. These were just thin wrappers added to workaround the problem. Without them the exported functions are just native MTA ones (so native `startResource` and so on).

2022-12-29 21:12 UTC, patrikjuvonen approved these changes

2022-12-29 21:12 UTC, patrikjuvonen commented
Thank you.

2022-12-29 21:12 UTC, merged