editor_main: Improve scripting extensions
multitheftauto/mtasa-resources pull request #385
Opened 2022-04-18 02:00 UTC by srslyyyy

2022-04-18 15:56 UTC, patrikjuvonen requested changes

2022-04-18 15:56 UTC, patrikjuvonen commented on [editor]/editor_main/client/mapEditorScriptingExtension_c.lua
> +-- VERSION: RemoveWorldObjects (v1) AutoLOD (v1) BreakableObjects (v1)
Probably worth bumping the version while at it, since something is being changed.
```suggestion
-- VERSION: RemoveWorldObjects (v1) AutoLOD (v2) BreakableObjects (v1)

```

2022-04-18 15:56 UTC, patrikjuvonen commented on [editor]/editor_main/server/mapEditorScriptingExtension_s.lua
> +-- VERSION: RemoveWorldObjects (v1) AutoLOD (v1)
Probably worth bumping the version while at it, since something is being changed.
```suggestion
-- VERSION: RemoveWorldObjects (v1) AutoLOD (v2)

```

2022-04-18 15:56 UTC, patrikjuvonen commented on [editor]/editor_main/server/mapEditorScriptingExtension_s.lua
> +function onPlayerResourceStart(resourceElement)
Would a local function work?
```suggestion
local function onPlayerResourceStart(resourceElement)

```

2022-04-18 15:56 UTC, patrikjuvonen commented on [editor]/editor_main/server/mapEditorScriptingExtension_s.lua
> +		return false
This function shouldn't return any _thing_.
```suggestion
		return

```

2022-04-22 09:11 UTC, patrikjuvonen approved these changes

2022-06-14 00:12 UTC, jlillis commented on [editor]/editor_main/server/mapEditorScriptingExtension_s.lua
> +addEventHandler("onPlayerResourceStart", root, onPlayerResourceStart)
I think this should be attached to `resourceRoot` so it is only triggered when this map resource starts.

2022-06-17 05:58 UTC, srslyyyy commented on [editor]/editor_main/server/mapEditorScriptingExtension_s.lua
> +addEventHandler("onPlayerResourceStart", root, onPlayerResourceStart)
The source of this event is player, so i can't do that.

2022-06-18 05:23 UTC, jlillis commented on [editor]/editor_main/server/mapEditorScriptingExtension_s.lua
> +addEventHandler("onPlayerResourceStart", root, onPlayerResourceStart)
Ah. You're right, disregard.

2022-06-18 05:24 UTC, merged