IP2C standalone resource
multitheftauto/mtasa-resources pull request #405
Opened 2023-01-16 17:40 UTC by Fernando-A-Rocha

As @Dutchman101 suggested, ip2c is now its own resource.

- moved admin ip2c code to new resource + Updated scoreboard setting "Country" data.
- ip2c exported function getPlayerCountry used in scoreboard.
- admin2 implementation of ip2c not changed, just deleted duplicated flags in that resource which were unused.

2023-01-16 19:02 UTC, Fernando-A-Rocha commented
When someone tests this, let me know if the resource has any problem doing fileOpen. For me, it stopped working and I can't understand why.

2023-01-16 21:25 UTC, Fernando-A-Rocha commented
Let me know if you want anything changed, I'm all ears.

2023-01-16 22:21 UTC, Fernando-A-Rocha commented
I will look at #318 and try to fix the country flag images.

2023-01-21 21:23 UTC, Dutchman101 requested changes
We're awaiting feedback from this convo on development discord:
![image](https://user-images.githubusercontent.com/12105539/213887603-bf33cb59-fff9-470c-b884-d47233eefa27.png)
Either option has to be implemented, requesting input from @jlillis (AGENT_STEELMEAT)

2023-01-23 09:44 UTC, Fernando-A-Rocha commented
> We're awaiting feedback from this convo on development discord: ![image](https://user-images.githubusercontent.com/12105539/213887603-bf33cb59-fff9-470c-b884-d47233eefa27.png) Either option has to be implemented, requesting input from @jlillis (AGENT_STEELMEAT)

After further discussion, option 2 (placeholder function in admin) has been implemented (see bd1e9c578d449edc645e84a103416e24cfdb4a4b).

Ready for review.

2023-01-23 17:10 UTC, brenodanyel commented on [admin]/admin/server/admin_ip2c.lua
> +    return false
```suggestion
    local ip2c = getResourceFromName('ip2c')
    return ip2c and call(ip2c, 'getPlayerCountry', player)
```

Instead of just returning false, why not forward the call to the ip2c resource? This way if you have ip2c resource and your resources call ip2c from admin you get the deprecation warning but your scripts will not break

2023-01-23 17:19 UTC, Fernando-A-Rocha commented on [admin]/admin/server/admin_ip2c.lua
> +    return false
Done @brenodanyel

2023-01-25 00:00 UTC, jlillis approved these changes
Only have a few minor things worth considering but this is great work and ready to merge as is. Unless anyone has further feedback I'll merge it in 3 days.

2023-01-25 02:12 UTC, Fernando-A-Rocha commented on [admin]/admin/server/admin_server.lua
> +			stopResource(ip2c)
The way this is set up, the server administrator can only control if ip2c runs or not. It has a serverwide effect as other resources can use ip2c like scoreboard.
The server administrator can't just disable ip2c for the admin panel, at least not with the current set up.
I think it can stay as is 👍

2023-01-25 02:12 UTC, Fernando-A-Rocha commented on [admin]/admin/meta.xml
> +					desc="When enabled, ip2c resource runs and fetches player countries by IP."
Done

2023-01-25 02:13 UTC, Fernando-A-Rocha commented on [admin]/ip2c/meta.xml
> +    <!-- New Flags (added 17 January, 2023) -->
Affirmative

2023-01-28 01:13 UTC, merged