Improved Msgbox
multitheftauto/mtasa-resources pull request #464
Opened 2024-01-28 01:02 UTC by Nico8340

This PR removes the old msgbox resource and creates a new one that provides a much simpler concept and looks better.
Available types: info, question, warning, error
Available buttons: ok, okcancel, retrycancel, yesno, yesnocancel
![Képernyőkép 2024-01-28 012351](https://github.com/multitheftauto/mtasa-resources/assets/122193236/6fba2f8b-7748-4523-90ac-aa15d2c16eaa)

2024-01-28 01:07 UTC, Nico8340 commented
A set of pictures of the new look in action (default resources)
![image](https://github.com/multitheftauto/mtasa-resources/assets/122193236/d4b8261d-d341-4bc7-8d60-e5edf4d69fcf)
![image](https://github.com/multitheftauto/mtasa-resources/assets/122193236/05464eb0-ed93-4a67-9a40-ded9cb61a1c7)
![image](https://github.com/multitheftauto/mtasa-resources/assets/122193236/d740faf2-6485-48a1-bc62-2aae56525a2f)

2024-01-28 09:12 UTC, Fernando-A-Rocha commented
Good job! I would just add more spacing between the title and message, as well as the icon on the left @Nico8340

2024-01-28 14:13 UTC, Nico8340 commented
> Good job! I would just add more spacing between the title and message, as well as the icon on the left @Nico8340

Should there be more space vertically or horizontally?
@Fernando-A-Rocha

2024-01-28 14:32 UTC, Fernando-A-Rocha commented
> > Good job! I would just add more spacing between the title and message, as well as the icon on the left @Nico8340
> 
> Should there be more space vertically or horizontally?
> @Fernando-A-Rocha 

On the y axis between the 2 text labels, and on the x axis between the image and the texts, imo @Nico8340

2024-01-28 15:04 UTC, Nico8340 commented
> > > Good job! I would just add more spacing between the title and message, as well as the icon on the left @Nico8340
> > 
> > 
> > Should there be more space vertically or horizontally?
> > @Fernando-A-Rocha
> 
> On the y axis between the 2 text labels, and on the x axis between the image and the texts, imo @Nico8340

Does they look better now? 😄 
![image](https://github.com/multitheftauto/mtasa-resources/assets/122193236/afd11475-7d09-4a74-a884-299895892680)

2024-01-28 16:25 UTC, Fernando-A-Rocha commented
> > On the y axis between the 2 text labels, and on the x axis between the image and the texts, imo @Nico8340
> 
> Does they look better now? 😄 
> @Fernando-A-Rocha 
> ![image](https://github.com/multitheftauto/mtasa-resources/assets/122193236/afd11475-7d09-4a74-a884-299895892680)
> 

I think it looks fine now

2024-01-28 16:29 UTC, Fernando-A-Rocha commented
There is no way to handle when a player clicked a specific button like Ok, Cancel? Seems like all they do is close the window

2024-01-28 16:51 UTC, Nico8340 commented
> There is no way to handle when a player clicked a specific button like Ok, Cancel? Seems like all they do is close the window

Of course, it is possible to handle the buttons, the function returns three variables that contain the buttons, and the onClientGUIClick event can be used to handle the responses. They only closes so that the scripts do not have to handle this separately.

2024-01-28 20:12 UTC, Nico8340 commented
By the way, I would like to use this system for the new chat implementation as well, in case of mute, notify the player to end this activity or he will face a bigger sanction.

2024-01-31 05:17 UTC, jlillis requested changes
Looks good overall, just a few minor notes. This implementation will work just fine in `editor_gui` and similar resources, but the `admin` and `admin2` resources have their own unique implementations that make use of coroutines that can't be easily replaced by this resource.

2024-01-31 05:17 UTC, jlillis commented on [editor]/editor_gui/client/me_gui.lua
>  	playSoundFrontEnd ( 5 )
Perhaps `msgbox` should make the calls to `playSoundFrontEnd` so behavior is consistent regardless of the calling resource?

2024-01-31 05:17 UTC, jlillis commented on [gameplay]/msgbox/meta.xml
> +    <script src="sourceC.lua" type="client" cache="false" />
This file isn't security-critical (imo) so I think this should be cacheable.

2024-01-31 05:17 UTC, jlillis commented on [gameplay]/msgbox/meta.xml
> +
For the rare and unlikely case other resources by others (outside this repo) used the original `msgbox` exports you should consider re-adding the old syntax as a backwards-compatible alternative.

2024-01-31 05:17 UTC, jlillis commented on [gameplay]/msgbox/sourceC.lua
> +        outputDebugString("Bad argument @ 'createMessageBox' [Expected string at argument 1, got " .. type(boxTitle) .. "]", 2)
For these checks consider using `error(message, 2)`. This will invoke an error in the calling resource rather than within `msgbox`, making debugging easier.

2024-01-31 05:17 UTC, jlillis commented on [gameplay]/msgbox/sourceC.lua
> +    local boxWidth = 350
I think these static values could be defined in a table at the top of script rather than in this function.

2024-01-31 14:32 UTC, Nico8340 commented on [gameplay]/msgbox/sourceC.lua
> +        outputDebugString("Bad argument @ 'createMessageBox' [Expected string at argument 1, got " .. type(boxTitle) .. "]", 2)
Done

2024-01-31 14:40 UTC, Nico8340 commented on [editor]/editor_gui/client/me_gui.lua
>  	playSoundFrontEnd ( 5 )
Done

2024-01-31 14:40 UTC, Nico8340 commented on [gameplay]/msgbox/sourceC.lua
> +    local boxWidth = 350
Done

2024-01-31 14:41 UTC, Nico8340 commented on [gameplay]/msgbox/meta.xml
> +    <script src="sourceC.lua" type="client" cache="false" />
Done

2024-01-31 14:49 UTC, Nico8340 commented on [gameplay]/msgbox/meta.xml
> +
Done

2024-01-31 15:21 UTC, Nico8340 commented
The changes have been made, but for some reason GitHub says they haven't.

2024-02-02 17:56 UTC, Nico8340 commented
I'm closing this pull request because I have a much better idea for the implementation that is completely different from this one.

2024-02-02 17:56 UTC, closed without merging