Add option to disable default report system.
multitheftauto/mtasa-resources pull request #472
Opened 2024-04-19 18:37 UTC by CArg22

Adds option "reportsEnabled" that can be used to disable or enabled default reports. Often servers are implementing this kind of system by themself so to do not duplicate functionality they can easily disable default report system.

2024-04-20 13:46 UTC, FileEX commented
The idea is good because now you have to manually fiddle with the file to disable the default reports. Many servers have their own reporting systems, which makes reports from the admin panel unnecessary and the ability to turn them off is good.

If the code will be revised and tested it can also be forward-ported to admin2

2024-05-09 21:11 UTC, Nico8340 commented on [admin]/admin/client/gui/admin_report.lua
> +*	Original File by lil_Toady|CArg22
If the original code was not created by you, I don't think you should write your name in it, but let's hear other people's opinions about it.

2024-05-09 21:17 UTC, Lpsd commented on [admin]/admin/client/gui/admin_report.lua
> +*	Original File by lil_Toady|CArg22
Yeah please revert this

2024-05-09 21:21 UTC, Lpsd requested changes

2024-05-09 21:21 UTC, Lpsd commented on [admin]/admin/server/admin_report.lua
> +**************************************]]
Remove this 2006 block comment, it's bigger than the code itself.

2024-05-10 03:09 UTC, jlillis requested changes
I like the idea but have a few issues with this PR as is:
1 - There isn't a clear indication to other admins/moderators that the reporting system is disabled anywhere in the UI.
2 - If this change is made for `admin`, it should also be made for `admin2`.

2024-05-10 03:09 UTC, jlillis commented on [admin]/admin/client/gui/admin_report.lua
> -addCommandHandler ( "report", aReport )
Removing this command handler removes functionality that some users may want to use. I would put this back.

2024-05-10 03:09 UTC, jlillis commented on [admin]/admin/client/gui/admin_report.lua
> +)
This could be shortened to `addEventHandler("onClientReports, resourceRoot, aReport)`. No need for an anonymous function here.

2024-05-10 03:09 UTC, jlillis commented on [admin]/admin/meta.xml
> +					/>
Some grammar improvements could be made here:
`friendlyname="Enable default reporting system"
desc="When enabled, players will be able to submit reports to admins via the /report command."`

2024-06-02 13:30 UTC, Nico8340 commented
Any updates on this?

2024-06-20 22:29 UTC, Dutchman101 commented
Superseded by #501

2024-06-20 22:29 UTC, closed without merging