basic security resource as a foundation
multitheftauto/mtasa-resources pull request #528
Opened 2024-07-29 14:14 UTC by ffsPLASMA

As the notes say, this resource aims to be a barebone security foundation for server owners to enhance and adapt on for their personal gamemodes. As recent times showed, security needs to be highlighted more and this resource should give a base start point for developers to work on. It only covers the most basic events and logs them.

2024-07-29 14:19 UTC, Fernando-A-Rocha commented
You are basically implementing these principles 
https://wiki.multitheftauto.com/wiki/Script_security

2024-07-29 14:20 UTC, Fernando-A-Rocha commented
I suggested this on mta dev discord and people discussed it. Some said it is not enough to make a server secure, that is correct, it's a foundation as PLASMA stated here in this PR. I believe it makes sense to have this resource in the default resources pack. It's essential nowadays on all servers.

2024-07-29 14:26 UTC, Fernando-A-Rocha commented
Previous discussion here: https://discord.com/channels/801330706252038164/801407272483291136/1248315073844220084

2024-07-29 14:29 UTC, ffsPLASMA commented
Yes its not a solution to cheating, nor should it be considered. its just a base with some useful events to catch potential abusive players and build upon it. I always wondered why nothing of such sorts were included by default.

2024-07-29 16:11 UTC, Nico8340 commented on [admin]/security/logging.lua
> +	fileFlush(uFileHandle);
There is no need to use the `fileFlush` function because you close the file immediately

2024-07-29 16:11 UTC, Nico8340 commented on [admin]/security/logging.lua
> +	fileFlush(uFileHandle);
There is no need to use the `fileFlush` function because you close the file immediately (same as above)

2024-07-29 16:11 UTC, Nico8340 commented on [admin]/security/logging.lua
> +	return "["..tostring(iDay).."."..tostring(iMonth).."."..tostring(iYear).." - "..tostring(iHour)..":"..tostring(iMinute)..":"..tostring(iSecond).."]";
How about using `string.format` instead?

2024-07-29 16:11 UTC, Nico8340 commented on [admin]/security/players.lua
> +	end
How about using a simple conditional check here?
```suggestion
logViolation(source, "Network interruption has " .. ((iStatus == 0) and "began" or "stopped") .. " after " .. iTicks .. " ticks")
```

2024-07-29 17:12 UTC, ffsPLASMA commented on [admin]/security/players.lua
> +	end
I used branch so people can further decide on what to do in case this event triggers.

2024-07-29 17:13 UTC, ffsPLASMA commented on [admin]/security/logging.lua
> +	return "["..tostring(iDay).."."..tostring(iMonth).."."..tostring(iYear).." - "..tostring(iHour)..":"..tostring(iMinute)..":"..tostring(iSecond).."]";
dunno, looks like cosmetic bias depending on different people. it works fine afterall.

2024-07-29 18:10 UTC, Nico8340 commented on [admin]/security/logging.lua
> +	return "["..tostring(iDay).."."..tostring(iMonth).."."..tostring(iYear).." - "..tostring(iHour)..":"..tostring(iMinute)..":"..tostring(iSecond).."]";
> dunno, looks like cosmetic bias depending on different people. it works fine afterall.

If you prefer it that way, you can keep it

2024-07-29 18:10 UTC, Nico8340 commented on [admin]/security/players.lua
> +	end
> I used branch so people can further decide on what to do in case this event triggers.

It's fair enough

2024-07-29 18:16 UTC, ffsPLASMA commented on [admin]/security/logging.lua
> +	fileFlush(uFileHandle);
removed

2024-07-29 18:16 UTC, ffsPLASMA commented on [admin]/security/logging.lua
> +	fileFlush(uFileHandle);
removed

2024-08-06 14:51 UTC, jlillis requested changes
I get the intent here but I really don't see this as a useful resource. If all it is doing is logging potentially problematic behavior. For this to be useful, it should really be integrated into admin/admin2 and take some action by default.

2024-08-14 19:13 UTC, Dutchman101 commented
> I get the intent here but I really don't see this as a useful resource. If all it is doing is logging potentially problematic behavior. For this to be useful, it should really be integrated into admin/admin2 and take some action by default.

This is just the beginning, after we see results from varying servers and gamemodes, the logging sensitivity may be tweaked to the point it's suitable for violation to lead to an action (or specific violation subtypes, definable by the server owner, as appropiate for their gamemode). Also, if we add universal, generic security checks that aren't mainly to raise an alert but to make a certain cheat effect impossible or violate on it, the code will grow expotentially as well as it will do down the line anyways, as again this is a very early version and there's much more to do here; it's better in a dedicated resource than bloating admin, or having to mind its structure when expanding it.

Really more of a "good to have, why not" thing at this point, and it can become really of value as it gets expanded to cover way more types of things.

2024-08-14 19:13 UTC, merged