editor: Fix EDF custom elements rotation issues on undo/manual Adjustment
multitheftauto/mtasa-resources pull request #546
Opened 2024-09-03 19:49 UTC by q8X

This PR fixes EDF rotation issue when setting the rotation manually or undoing an element, this could happen if you:
1. rotate > undo  > rotate after undoing
2. rotate > set rotation (F3) > rotate

This bug caused by a change in commit #400 

### **A video explains how the bug works**
I used the race spawnpoint as an example

https://github.com/user-attachments/assets/8207c082-0cd2-4ed1-957a-93c9ef0904b6

2024-09-07 22:36 UTC, jlillis requested changes
Everything looks good, just a minor nitpick about some whitespace changes.

2024-09-07 22:36 UTC, jlillis commented on [editor]/move_keyboard/move_keyboard.lua
> -
Looks like you have some unintended whitespace changes. Mind cleaning these up?

2024-09-08 09:35 UTC, q8X commented on [editor]/move_keyboard/move_keyboard.lua
> -
done

2024-09-16 13:58 UTC, jlillis approved these changes

2024-09-16 13:58 UTC, merged