Fix chat messages sent twice
multitheftauto/mtasa-resources pull request #566
Opened 2024-10-19 08:20 UTC by Fernando-A-Rocha

Fixes #460 

playercolors will no longer handle chat, as this is handled in the gamemode resource itself (freeroam), playercolors is just an extra resource.

@Dark-Dragon

2024-10-19 08:26 UTC, Fernando-A-Rocha commented
Other game modes that handle and output chat to chatbox are:
- TDM
- CTV
- Assault

Then, `admin` and `webstats` also handle onPlayerChat but don't alter its output.

2024-10-19 09:39 UTC, Dark-Dragon commented
Appropriate fix for while we wait for the large scale changes discussed in #463

2024-10-19 11:45 UTC, Fernando-A-Rocha commented
Exactly, this can be merged now.

2024-10-19 22:49 UTC, jlillis requested changes

2024-10-19 22:49 UTC, jlillis commented on [gameplay]/playercolors/playercolors.lua
> -		if type == 0 then
I think it would be better to just add an early return if `freeroam` is running, as this would break functionality on resources other than `freeroam`. Not that it's important functionality, I guess.

2024-10-20 00:35 UTC, Fernando-A-Rocha commented on [gameplay]/playercolors/playercolors.lua
> -		if type == 0 then
I can't think of a reason you would need playercolors to handle chat for you, running alongside other resources... 🤔 To me, it's a bug that this PR fixes.

2024-11-04 13:11 UTC, Fernando-A-Rocha commented
@jlillis do you agree with my comment above?

2024-11-05 00:30 UTC, jlillis commented on [gameplay]/playercolors/playercolors.lua
> -		if type == 0 then
You would need it to if you expect the player's nametag colors to appear in chat in gamemodes other than `freeroam`.

2024-11-11 13:41 UTC, Fernando-A-Rocha commented on [gameplay]/playercolors/playercolors.lua
> -		if type == 0 then
> I think it would be better to just add an early return if `freeroam` is running, as this would break functionality on resources other than `freeroam`. Not that it's important functionality, I guess.

Ok

2024-11-13 21:13 UTC, Fernando-A-Rocha commented
There you have it @jlillis

2024-11-13 21:14 UTC, jlillis approved these changes

2024-11-13 21:15 UTC, merged