voice_local: Fixes and improvements
multitheftauto/mtasa-resources pull request #575
Opened 2024-11-15 16:18 UTC by Fernando-A-Rocha

## Security fixes and enhancements

List: wip

I encourage you to test this resource with at least 1 other player.

2024-11-16 00:12 UTC, Dutchman101 commented
The talking icon should remain above any *actively talking* player's head. Even for the local player itself while they are speaking into mic using the voice_ptt bind.

Please keep feature parity, so that means the above, and removing "VOICE: " texts in the bottom of the screen.
Thanks for refactoring!
@Fernando-A-Rocha

2024-11-16 00:55 UTC, Fernando-A-Rocha commented
Aww I thought voice text in the bottom of the screen was a good idea. Can I leave it in as optional and disabled by default through meta.xml settings?

2024-11-18 23:39 UTC, Dutchman101 commented
I've tested and it appears not to be working
Remote players don't hear me, and don't see the speaking icon above my head (while it shows locally). While it works for current version

Your refactored version is bugged still... @Fernando-A-Rocha

2024-11-18 23:53 UTC, Fernando-A-Rocha commented
I will perform multiplayer tests again and get back to you. I was using a VM and it's sketchy to get to hear myself... Don't worry, this will be resolved.

2024-11-19 11:11 UTC, Fernando-A-Rocha commented
@Dutchman101 Tested. Please give feedback.

Video: https://www.youtube.com/watch?v=ZsMdG7jf-tI

2024-11-19 11:12 UTC, Fernando-A-Rocha commented
I added a necessary voice boost (multiplier) set to 6.0.
Voice sound volumes at 1.0 cannot be heard, a boost is required.

2024-11-20 20:58 UTC, ds1-e requested changes
Some smaller changes

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/client.lua
> +        triggerServerEvent("voice_local:addToPlayerBroadcast", resourceRoot, source)
```suggestion
        triggerServerEvent("voice_local:addToPlayerBroadcast", localPlayer, source)
```

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/client.lua
> +        triggerServerEvent("voice_local:removeFromPlayerBroadcast", resourceRoot, source)
```suggestion
        triggerServerEvent("voice_local:removeFromPlayerBroadcast", localPlayer, source)
```

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/client.lua
> +    triggerServerEvent("voice_local:setPlayerBroadcast", resourceRoot, streamedPlayers)
```suggestion
    triggerServerEvent("voice_local:setPlayerBroadcast", localPlayer, streamedPlayers)
```

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/client.lua
> +        triggerServerEvent("voice_local:removeFromPlayerBroadcast", resourceRoot, source)
```suggestion
        triggerServerEvent("voice_local:removeFromPlayerBroadcast", localPlayer, source)
```

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/server.lua
> +        triggerClientEvent(source, "voice_local:updateSettings", resourceRoot, settings)
```suggestion
        triggerClientEvent(source, "voice_local:updateSettings", source, settings)
```

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/server.lua
> +    triggerClientEvent(broadcasts[source], "voice_local:onClientPlayerVoiceStart", resourceRoot, source)
```suggestion
    triggerClientEvent(broadcasts[source], "voice_local:onClientPlayerVoiceStart", source, source)
```

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/server.lua
> +    triggerClientEvent(broadcasts[source], "voice_local:onClientPlayerVoiceStop", resourceRoot, source)
```suggestion
    triggerClientEvent(broadcasts[source], "voice_local:onClientPlayerVoiceStop", source, source)
```

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/server.lua
> +addEventHandler("voice_local:setPlayerBroadcast", resourceRoot, function(players)
```suggestion
addEventHandler("voice_local:setPlayerBroadcast", root, function(players)
```

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/server.lua
> +addEventHandler("voice_local:addToPlayerBroadcast", resourceRoot, function(player)
```suggestion
addEventHandler("voice_local:addToPlayerBroadcast", root, function(player)
```

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/server.lua
> +addEventHandler("voice_local:removeFromPlayerBroadcast", resourceRoot, function(player)
```suggestion
addEventHandler("voice_local:removeFromPlayerBroadcast", root, function(player)
```

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/client.lua
> +addEventHandler("voice_local:onClientPlayerVoiceStart", resourceRoot, function(player)
```suggestion
addEventHandler("voice_local:onClientPlayerVoiceStart", root, function(player)
```

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/client.lua
> +addEventHandler("voice_local:onClientPlayerVoiceStop", resourceRoot, function(player)
```suggestion
addEventHandler("voice_local:onClientPlayerVoiceStop", root, function(player)
```

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/client.lua
> +addEventHandler("voice_local:updateSettings", resourceRoot, function(settingsFromServer)
```suggestion
addEventHandler("voice_local:updateSettings", localPlayer, function(settingsFromServer)
```

In this case event is sent only to localPlayer

2024-11-20 20:58 UTC, ds1-e commented on [gameplay]/voice_local/client.lua
> +    triggerServerEvent("voice_local:setPlayerBroadcast", resourceRoot, streamedPlayers)
Simply use localPlayer

2024-11-21 11:15 UTC, Fernando-A-Rocha commented
I've applied your event handler source suggestions @ds1-e

2024-11-21 17:56 UTC, ds1-e approved these changes

2024-11-21 21:10 UTC, Dutchman101 commented
Thanks for addressing everything, it works fine after testing too.

2024-11-21 21:10 UTC, merged

2024-11-21 22:07 UTC, Fernando-A-Rocha commented
> Thanks for addressing everything, it works fine after testing too.

I'm glad!

Guys, please suggest new features for this resource. I will happily make a new PR.

Reminder: it's a default local 3D voice system, intended to be used by any server, suitable for roleplay, freeroam etc.

Some ideas:
- add conditions, functions and events to determine when a player can't talk (mute), e.g. when dead or knocked out (RP servers)
- add customizable on-screen text/icons to display when the voice is being used, like many games do, aside from the icon above player head which can be unwanted (right now it can be disabled)
- shout and whisper modes
- voice effects 
- customizable radio channels or player-to-player voice to simulate phone calls

2024-12-04 01:01 UTC, Dutchman101 commented
@Fernando-A-Rocha
The resource still suffers from a bug that was present in the initial version, that you can sometimes hear random player's voices (when no one is near you; those players being on the other side of the map). I got reports about it again, and then witnessed a case of it occuring.

2025-01-01 11:55 UTC, Fernando-A-Rocha commented
Can someone please review the code to get more opinions on why the situation described by @Dutchman101 happens?